### ISSUE TITLE
Neuron export fails

### ISSUE THREAD

**Issue by epiasini** [epiasini/neuroml_use_case#1]
Simulating with `jnml simulation.xml` works as intended. On the other hand, `jnml simulation.xml -neuron` fails with the following output:

```
~/.../neuroml_use_case> jnml simulation.xml 
 jNeuroML v0.3.5
(INFO) Reading from: /home/eugenio/phd/code/neuroml_use_case/simulation.xml
(INFO) Adding simulation Component(id=sim type=Simulation) of network/component: network (Type: network)
(INFO) popsOrComponents: [Component(id=GrCPop type=population), Component(id=SpikeRecorderPop type=population), Component(id=mossySpikersPopOFF type=population), Component(id=mossySpikersPopON type=population)]
(INFO) No child of synapses
(INFO) Writing to: iafRefCell.mod
(INFO) No child of synapses
(INFO) Writing to: iafRefCell.mod
(INFO) Writing to: spikeGeneratorRefPoisson.mod
(INFO) Writing to: spikeGeneratorRefPoisson.mod
Recording v on cell 0 in GrCPop of type Component(id=IaF_GrC type=iafRefCell)
Recording spikeRecorder on cell 0 in SpikeRecorderPop of type Component(id=IaF_GrC type=iafRefCell)
org.lemsml.jlems.core.sim.ContentError: No such exposure spikeRecorder in ComponentType, name=iafRefCell (Integrate and fire cell  with capacitance _C, _leakConductance, _leakReversal and refractory period _refract) extends iafCell 
         refract (time) 
         leakConductance (conductance) 
         leakReversal (voltage) 
         thresh (voltage) 
         reset (voltage) 
         C (capacitance) 
    at org.lemsml.jlems.core.type.ComponentType.getExposure(ComponentType.java:712)
    at org.neuroml.export.neuron.NeuronWriter.generate(NeuronWriter.java:328)
    at org.neuroml.export.neuron.NeuronWriter.getMainScript(NeuronWriter.java:93)
    at org.neuroml.JNeuroML.main(JNeuroML.java:353)
```

**Comment by pgleeson** [comment]
Out of date... 

simulation.xml no longer required..?
